#!/usr/bin/env bun

// Required parameters:
// @raycast.schemaVersion 1
// @raycast.title Ask Quick Question
// @raycast.mode fullOutput

// Optional parameters:
// @raycast.icon https://openai.com/favicon.ico
// @raycast.packageName ChatGPT
// @raycast.argument1 { "type": "text", "placeholder": "Question?" }

import { run2 } from "..";

if (process.argv[2]) await run2("python", { args: `--question "${process.argv[2]}"`, fileName: "ask", preExecScript: ["SOURCE_COMMONRC"] });
else await run2("python", { fileName: "ask", preExecScript: ["SOURCE_COMMONRC"] });
