#!/usr/bin/env bun

// Required parameters:
// @raycast.schemaVersion 1
// @raycast.title Generate Unique Email
// @raycast.mode fullOutput

// Optional parameters:
// @raycast.icon 📥
// @raycast.argument1 { "type": "text", "placeholder": "Your Name", "optional": true }
// @raycast.argument2 { "type": "text", "placeholder": "Domain. maildrop.cc", "optional": true }
// @raycast.packageName Developer Utils

import { runLogin, runNonLogin } from "./0";

await runNonLogin("generate_unique_email.py");
