#!/usr/bin/env bun

// Required parameters:
// @raycast.schemaVersion 1
// @raycast.title Generate Text With Line
// @raycast.mode fullOutput

// Optional parameters:
// @raycast.icon ⌨️
// @raycast.argument1 { "type": "text", "placeholder": "How many times?" }
// @raycast.argument2 { "type": "text", "placeholder": "What text?" }

import { run2 } from "..";

await run2("python", { fileName: "generate_text_with_line" });
