#!/Users/mohammadtahsin/.bun/bin/bun

// Required parameters:
// @raycast.schemaVersion 1
// @raycast.title Get git branch name
// @raycast.mode fullOutput

// Optional parameters:
// @raycast.icon https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png
// @raycast.argument1 { "type": "text", "placeholder": "Task ID", "optional": true }
// @raycast.argument2 { "type": "text", "placeholder": "Title" }

import { runLogin, runNonLogin } from "./0";

await runLogin("get_git_branch_name.py");
