#!/usr/bin/env bun

// Required parameters:
// @raycast.schemaVersion 1
// @raycast.title Get git branch name
// @raycast.mode fullOutput

// Optional parameters:
// @raycast.icon https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png
// @raycast.argument1 { "type": "text", "placeholder": "Task ID", "optional": true }
// @raycast.argument2 { "type": "text", "placeholder": "Title" }

import { run } from "..";

await run("python", { fileName: "get_git_branch_name" });
