#!/Users/mohammadtahsin/.bun/bin/bun

// Required parameters:
// @raycast.schemaVersion 1
// @raycast.title Generate Random Joke
// @raycast.mode fullOutput

// Optional parameters:
// @raycast.icon 🃏
// @raycast.needsConfirmation false

import { runLogin, runNonLogin } from "./0";

await runNonLogin("joke.py");
