#!/usr/bin/env bun

// Required parameters:
// @raycast.schemaVersion 1
// @raycast.title Kill port
// @raycast.mode compact

// Optional parameters:
// @raycast.icon 🔫
// @raycast.argument1 { "type": "text", "placeholder": "Port number" }

import { run2 } from "..";
await run2("python", { fileName: "kill_process_by_port" });
