#!/usr/bin/env bun

// Required parameters:
// @raycast.schemaVersion 1
// @raycast.title Loop
// @raycast.mode fullOutput

// Optional parameters:
// @raycast.icon 🔁
// @raycast.argument1 { "type": "text", "placeholder": "count" }
// @raycast.argument2 { "type": "text", "placeholder": "command" }
// @raycast.argument3 { "type": "text", "placeholder": "wait interval", "optional": true }

import { run } from "..";

await run("python", { fileName: "loop" });
