#!/usr/bin/env bun

// Required parameters:
// @raycast.schemaVersion 1
// @raycast.title Remind
// @raycast.mode fullOutput

// Optional parameters:
// @raycast.icon ⏲️
// @raycast.argument1 { "type": "text", "placeholder": "text" }

import { run2 } from "..";

await run2("python", { fileName: "remind" });
