#!/bin/sh -l

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Spell Number
# @raycast.mode fullOutput

# Optional parameters:
# @raycast.icon #
# @raycast.argument1 { "type": "text", "placeholder": "Number?" }

# Documentation:
# @raycast.author tahsin
# @raycast.authorURL https://raycast.com/tahsin

BASEDIR=$(dirname "$0")
SCRIPT="spell_num.py"

if [ -z "$*" ]; then
    python3 -B "$BASEDIR"/../src/"$SCRIPT"
else
    python3 -B "$BASEDIR"/../src/"$SCRIPT" --number "$@"
fi
