#!/usr/bin/env bun

// Required parameters:
// @raycast.schemaVersion 1
// @raycast.title Spell Number
// @raycast.mode fullOutput

// Optional parameters:
// @raycast.icon #
// @raycast.argument1 { "type": "text", "placeholder": "Number?" }

// ask.sh in current dir
// BASEDIR=$(dirname "$0")

import { runLogin, runNonLogin } from "./0";

await runNonLogin("spell_num.py");
