#!/usr/bin/env bun

// Required parameters:
// @raycast.schemaVersion 1
// @raycast.title Spell Number
// @raycast.mode fullOutput

// Optional parameters:
// @raycast.icon #
// @raycast.argument1 { "type": "text", "placeholder": "Number?" }

// ask.sh in current dir
// BASEDIR=$(dirname "$0")

import { run } from "..";

let args = Number(process.argv[2]) ? `--number ${process.argv[2]}` : undefined;
await run("python", { fileName: "spell_num", args });
