#!/usr/bin/env bun

// Required parameters:
// @raycast.schemaVersion 1
// @raycast.title Test
// @raycast.mode fullOutput

// Optional parameters:
// @raycast.icon 🛠️
// @raycast.packageName Developer Utils

import { runLogin, runNonLogin } from "..";

await runLogin("t.py");
