name: scripts-pipeline

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.10]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Check Runtime
        run: |
          bun --version
          python3 --version

      - name: Install dependencies
        run: |
          bun install
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install -r requirements.txt

      - name: Test
        run: |
          bun run test
